[package]
name = "bevy_spritesheet_animation"
version = "0.4.3"
description = "A Bevy plugin for animating sprites"
repository = "https://github.com/merwaaan/bevy_spritesheet_animation"
readme="README.md"
license = "MIT"
keywords = ["bevy", "sprite", "animation"]
categories = ["game-development"]
edition = "2021"
resolver = "2"
exclude = [
  "assets/example.gif",
  "assets/example3d.gif"
]

[dependencies]
bevy = { version = "0.14.0", default-features = false, features = ["bevy_pbr", "bevy_sprite"] }

[dev-dependencies]
approx = "0.5.1"
bevy = { version = "0.14.0", default-features = true }
clap = { version = "4.5.16", features = ["derive"] }
divan = "0.1.14"
iyes_perf_ui = "0.3.0"
rand = "0.8.5"

[profile.test]
inherits = "release"

[[bench]]
name = "basic"
harness = false

[lints]
clippy.type_complexity = "allow"
