[package]
name = "bevy_spritesheet_animation"
version = "0.4.0"
description = "A Bevy plugin for animating sprites"
repository = "https://github.com/merwaaan/bevy_spritesheet_animation"
readme="README.md"
license = "MIT"
keywords = ["bevy", "sprite", "animation"]
categories = ["game-development"]
edition = "2021"
resolver = "2"
exclude = [
  "example.gif"
]

[dependencies]
bevy = { version = "0.14.0", default-features = false, features = ["bevy_pbr", "bevy_sprite"] }
itertools = "0.12.1"
visibility = "0.1.0"

[dev-dependencies]
approx = "0.5.1"
bevy = { version = "0.14.0", default-features = true }
criterion = "0.5.1"
rand = "0.8.5"

[profile.test]
inherits = "release"

[features]
# Enable this feature so that the tests/doctests get access to some private constructors.
#
# > cargo test --features integration-tests
integration-tests = []

[[bench]]
name = "basic"
harness = false
